### ISSUE TITLE
Some fields are too small!

### ISSUE THREAD

**Issue by nilsweb** [IF11I/backend#14]
While entering test data, I encountered an exception thrown due to fields being too small for 'regular' data. Please enlarge those fields (45 chars like the others) and/or return a correct ResponseMessage in the case of an error.

```
An exception occurred while executing
'INSERT INTO supplierEntity (name, strasse, plz, ort, telefon, mobil, fax, email) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'
with params ['Test Supplier', '123 My Street', '12345', 'Great City, XY', '(555) 123 456 789 - 0', '(555) 123 456 789 - 42', '(555) 123 456 789 - 4242', 'test@supplier.xyz']:

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'telefon' at row 1
```

**Comment by weinzierl-florian** [comment]
Do you have a complete list, which fileds exactly were to small?

Anyways I think I wrote them all as described in the ER-Model

**Comment by nilsweb** [comment]
I think it's just the supplier phone numbers (phone, mobile and fax).
